//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFizjoTerm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Referral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Referral()
        {
            this.Visit = new HashSet<Visit>();
        }

        public int IdReferral { get; set; }
        public int IdPatient { get; set; }
        [Display(Name = "Diagnoza")]
        public string Diagnosis { get; set; }
        [Display(Name = "ICD10")]
        public string Icd10 { get; set; }
        [Display(Name = "Liczba wizyt")]
        public int NbOfDays { get; set; }
        [Display(Name = "Data wystawienia")]
        [DataType(DataType.Date)]
        public System.DateTime DateReferral { get; set; }
        [Display(Name = "Data zapisu")]
        [DataType(DataType.Date)]
        public System.DateTime DateSaved { get; set; }
        [Display(Name = "Zlecone zabiegi")]
        public string Treatments { get; set; }
        [Display(Name = "Lekarz zlecaj¹cy")]
        public string Doctor { get; set; }
        [Display(Name = "Skierowanie zrealizowane")]
        public bool ReferralCompleted { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visit { get; set; }
    }
}
